### ISSUE TITLE
Inconsistent TEG and ZAS behavior

### ISSUE THREAD

**Issue by Snownbloodyflowers** [Citadel-Station-13/Citadel-Station-13-RP#1406] opened 2019-06-05 02:17 UTC
#### Brief description of the issue
SME TEG coolant loop behavior is inconsistent with the conservation of energy. 

#### What you expected to happen
The cooling loop input of the SME's TEGs should have lower temperatures in the input of the coolant loop than the output part of the coolant loop.

#### What actually happened
For one reason or another, the coolant input to the TEG will have a higher temperature by around a degree or two compared to the output loop while transferring heat from the hot loop of the SM

#### Steps to reproduce
- Setup the SM
- This bug occurs randomly, incidence rate is higher at higher temperatures.

#### Code Revision
- All
 
#### Anything else you may wish to add:
- Most likely relate to the old baystation bug regarding float point and temperatures (numbers in general) causing it to change into a negative kelvin value.

**Comment by ForFoxSake** [comment] 2019-07-10 15:40
This is probably not a bug, depending on how the setup is constructed.
The radiators reduce heat in the loop universally, moving gas both ways until it reaches a pump.

Ergo, for systems where the pump pushes towards the teg after the radiators, the radiators are cooling the gas backward towards the teg output.
This means the calculation for the gas temperature on the output pipe is
`temperature of the input gas + temperature transferred from TEG - temperature of the gas already in the radiator`
It should be clear this can often correctly result in an output temperature lower than that inside the TEG.
I guess what I'm asking is: Was your pump before or after the radiator system?

**Comment by Snownbloodyflowers** [comment] 2019-07-12 04:25
The pump is the default setup. I believe that is after the radiator system (if you mean

**Comment by nik707** [comment] 2019-10-29 22:35
I'm gonna honestly close this because it seems like intended behaviour or at least something way too in depth to bother fixing with how little it matters

**Closed by nik707** 2019-10-29 22:35 UTC
